kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    DishListView,
    DishDetailView,
    CookListView,
    CookDetailView,
    update_dish,
    DishDeleteView,
    CookDeleteView,
    DishCreateView,
    toggle_assign_to_dish,
    register_request,
    update_cook,
    ChangePasswordView, CategoryDetailView, remove_cook_from_dish, remove_dish_from_cook,
)

urlpatterns = [
    path("", index, name="index"),
    path("register/", register_request, name="register"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>/",
         CategoryDetailView.as_view(),
         name="category-detail"
         ),
    path("categories/create/",
         CategoryCreateView.as_view(),
         name="category-create"
         ),
    path("categories/<int:pk>/update/",
         CategoryUpdateView.as_view(),
         name="category-update"
         ),
    path("categories/<int:pk>/delete/",
         CategoryDeleteView.as_view(),
         name="category-delete"
         ),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", update_dish, name="dish-update"),
    path("dishes/<int:pk>/delete/",
         DishDeleteView.as_view(),
         name="dish-delete"
         ),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", register_request, name="cook-create"),
    path("cooks/<int:pk>/update/", update_cook, name="cook-update"),
    path("cooks/<int:pk>/change-password/",
         ChangePasswordView.as_view(),
         name="change-password"
         ),
    path("cooks/<int:pk>/delete/",
         CookDeleteView.as_view(),
         name="cook-delete"
         ),
    path("dishes/<int:pk>/toggle-assign/",
         toggle_assign_to_dish,
         name="toggle-dish-assign"
         ),
    path("dishes/<int:dish_id>/remove-cook/<int:cook_id>/",
         remove_cook_from_dish,
         name="remove_cook_from_dish"
         ),
    path("dishes/<int:cook_id>/remove-dish/<int:dish_id>/",
         remove_dish_from_cook,
         name="remove_dish_from_cook"
         ),
]

app_name = "kitchen"

my_restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("kitchen.urls", namespace="kitchen")),
        path("accounts/", include("django.contrib.auth.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        verbose_name_plural = "categories"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    POSITION_CHOICES = {
        ("Chef", "Chef"),
        ("Cook", "Cook")
    }
    position = models.CharField(max_length=4, choices=POSITION_CHOICES, default="Cook")
    year_of_experience = models.IntegerField(null=True)
    photo = models.ImageField(null=True, blank=True, upload_to="cook_photo/")

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=63)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")
    picture = models.ImageField(
        null=True,
        blank=True,
        upload_to="dish_pictures/"
    )

    class Meta:
        verbose_name_plural = "dishes"
        ordering = ["category__name"]

    def __str__(self):
        return self.name

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Dish, Cook


class DishForm(forms.ModelForm):
    picture = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control-file'})
    )
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishUpdateForm(forms.ModelForm):
    picture = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control-file'})
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    photo = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control-file'}),
        label="",

    )

    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "year_of_experience",
            "photo"
        )


class CookUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Enter your name"})
    )
    photo = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={'class': 'form-control-file'})
    )

    class Meta:
        model = Cook
        fields = ['first_name', 'last_name', "year_of_experience", "photo"]


class CategoryNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class DishNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class CookUsernameSearchForm(forms.Form):
    username = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"})
    )

kitchen/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import (
    DishForm,
    CookCreationForm,
    CookUpdateForm,
    CategoryNameSearchForm,
    DishNameSearchForm,
    CookUsernameSearchForm, DishUpdateForm,
)
from kitchen.models import Category, Dish, Cook


def index(request):

    num_category = Category.objects.count()
    num_dish = Dish.objects.count()
    num_cook = Cook.objects.count()

    context = {
        "num_category": num_category,
        "num_dish": num_dish,
        "num_cook": num_cook,
    }
    return render(request, "kitchen/index.html", context=context)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    model = Category
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        context["search_form"] = CategoryNameSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        queryset = Category.objects.all()
        form = CategoryNameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    model = Category


class CategoryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy("kitchen:category-list")


class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy("kitchen:category-list")


class CategoryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Category
    success_url = reverse_lazy("kitchen:category-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    queryset = Dish.objects.select_related("category")
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        context["search_form"] = DishNameSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        queryset = Dish.objects.all()
        form = DishNameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    template_name = "kitchen/dish_create_form.html"
    success_url = reverse_lazy("kitchen:dish-list")


@login_required
def update_dish(request, pk):
    dish = get_object_or_404(Dish, id=pk)

    if request.method == 'POST':
        form = DishUpdateForm(request.POST, request.FILES, instance=dish)

        if form.is_valid():
            form.save()
            return redirect("kitchen:dish-detail", pk=dish.id)
    else:
        form = DishUpdateForm(instance=dish)

    return render(request, 'kitchen/dish_update_form.html', {'form': form})


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = CookUsernameSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Cook.objects.prefetch_related("dishes__category")
        form = CookUsernameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    template_name = 'kitchen/cook_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cook = self.get_object()
        dishes = cook.dishes.all()
        categories = list(set(dish.category for dish in dishes))
        context['categories'] = categories
        return context


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:index")


def register_request(request):
    if request.method == 'GET':
        form = CookCreationForm()
        return render(request, 'registration/register.html', {'form': form})

    if request.method == 'POST':
        form = CookCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('kitchen:index')
        else:
            return render(
                request,
                'registration/register.html',
                {'form': form}
            )


@login_required
def update_cook(request, pk):
    cook = Cook.objects.get(id=pk)

    if request.method == 'POST':
        form = CookUpdateForm(request.POST, request.FILES, instance=cook)

        if form.is_valid():
            form.save()
            return redirect("kitchen:cook-detail", pk=cook.id)
    else:
        form = CookUpdateForm(instance=request.user)

    return render(request, 'kitchen/cook_form.html', {'form': form})


class ChangePasswordView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    PasswordChangeView
):
    template_name = 'registration/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('kitchen:index')


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    if (
        Dish.objects.get(id=pk) in cook.dishes.all()
    ):
        cook.dishes.remove(pk)
    else:
        cook.dishes.add(pk)
    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))


@login_required
def remove_cook_from_dish(request, dish_id, cook_id):
    dish = get_object_or_404(Dish, id=dish_id)
    cook = get_object_or_404(Cook, id=cook_id)

    dish.cooks.remove(cook)
    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[dish_id]))


@login_required
def remove_dish_from_cook(request, cook_id,  dish_id):
    dish = get_object_or_404(Dish, id=dish_id)
    cook = get_object_or_404(Cook, id=cook_id)

    cook.dishes.remove(dish)
    return HttpResponseRedirect(reverse_lazy("kitchen:cook-detail", args=[cook_id]))

templates/kitchen/category_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} My Restaurant Kitchen Service {% endblock title %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

  <div class="page-header" style="margin-top: 300px">
  <div class="position-absolute fixed-top ms-auto w-50 h-100 rounded-3 z-index-0 d-none d-sm-none d-md-block me-n4" style="background-image: url('{% static 'img/dish_create_page.jpeg' %}'); background-size: cover;">
  </div>
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-7 d-flex justify-content-center flex-column">
        <div class="card card-body d-flex justify-content-center shadow-lg p-5 blur align-items-center">
          <h3 class="text-center">Delete category</h3>
          <form role="form" id="contact-form" method="post" autocomplete="off">
            <div class="card-body">
              <div class="row">
              <div class="mb-3">
                <h5 class="text-center">Are you sure you want to delete this category?</h5>
                <h6 class="text-center">All dishes from this category will be deleted as well.</h6>
                <br><br>
                <form action="" method="post">
                  {% csrf_token %}
                  <div class="col-md-12">
                    <a href="{% url "kitchen:category-list" %}"></a>
                    <button type="submit" class="btn bg-gradient-danger w-50">Delete</button><button type="reset" class="btn bg-gradient-dark w-50"><a href="{% url "kitchen:category-list" %}" style="color: #f8f9fa">Cancel</a></button>
                  </div>
                </form>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/kitchen/category_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %} class="blog-author bg-gray-100" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

<br><br>

{% block content %}
  <header class="bg-gradient-dark">
    <div class="page-header min-height-200" style="background-image: url('{% static 'img/curved1.jpg' %}');">
      <span class="mask bg-gradient-info opacity-5"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,1" />
          </g>
        </svg>
      </div>
    </div>
  </header>
<!-- -------- START Features w/ icons and text on left & gradient title and text on right -------- -->
<section class="py-9">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <h6 class="text-gradient text-dark mb-0 mt-2"> Category name</h6>
        <h3 class="text-gradient text-primary mb-0 mt-2">{{ category.name }}</h3>
        <br>
        <div class="row">
          <div class="col-md-4">
          <a href="{% url "kitchen:category-update" pk=category.id %}" class="btn btn-sm btn-outline-info">Update</a>
          </div>
          <div class="col-md-4" style="padding: unset">
            <a href="{% url "kitchen:category-delete" pk=category.id %}" class="btn btn-sm btn-outline-danger">Delete</a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 mt-lg-0 mt-5 ps-lg-0 ps-0">
        {% if category.dish_set %}
          <h3><strong>Dishes in this category:</strong></h3>
          {% for dish in category.dish_set.all %}
            <div class="p-1 info-horizontal">
              <div class="icon icon-shape rounded-circle bg-gradient-primary shadow text-center">
                <i class="fas fa-utensils opacity-10"></i>
              </div>
              <div class="description ps-3">
                <a href="{% url "kitchen:dish-detail" pk=dish.id %}">
                  <h4 class="mb-0 link-dark">{{ dish.name }}</h4>
                </a>
                <p><strong>Category:</strong> {{ dish.category.name }} <strong> Price:</strong> {{ dish.price }}</p>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p><strong>Oops, this category has no dishes!</strong></p>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/kitchen/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block body %} class="blog-author bg-gray-100" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

<br><br>

{% block content %}
  <header class="bg-gradient-dark">
    <div class="page-header min-height-300" style="background-image: url('{% static 'img/curved1.jpg' %}');">
      <span class="mask bg-gradient-info opacity-5"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,1" />
          </g>
        </svg>
      </div>
    </div>
  </header>
<!-- -------- START Features w/ icons and text on left & gradient title and text on right -------- -->
<section class="py-6">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <form action="" method="GET" class="form">
        <div class="input-group mb-0">
          <label for="name"></label>
          <input type="text" placeholder="Search by name" class="form-control" name="name" id="name" value="{{ search_form.name.value }}">
        </div>
      </form>
        <h3 class="text-gradient text-primary mb-0 mt-2">Check out dish category</h3>
        <h6><br></h6>
        <p>Pain is what we go through as we become older. We get insulted by others, lose trust for those others. We get back stabbed by friends. It becomes harder for us to give others a hand.</p>
        <a href="{% url "kitchen:category-create" %}" class="text-primary icon-move-right">Add new category
          <i class="fas fa-arrow-right text-sm ms-1"></i>
        </a>
      </div>
      <div class="col-lg-6 mt-lg-0 mt-5 ps-lg-0 ps-0">
      <div class="container" style="columns: 2">
      {% if category_list %}
        {% for category in category_list %}
          <div class="p-3 info-horizontal">
            <div class="icon icon-shape rounded-circle bg-gradient-primary shadow text-center">
              <i class="fas fa-tags opacity-10"></i>
            </div>
            <div class="description ps-3">
              <a href="{% url "kitchen:category-detail" pk=category.id%}">
                <h4 class="mb-0">{{ category.name }}</h4>
              </a>
              <br>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <p class="text-dark text-center">There are no categories!</p>
      {% endif %}

      </div>

      </div>
    </div>
  </div>
</section>


{% endblock content %}

templates/kitchen/dish_detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %} class="blog-author bg-gray-100" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

<br><br>

{% block content %}
  <header class="bg-gradient-dark">
    <div class="page-header min-height-200" style="background-image: url('{% static 'img/curved1.jpg' %}');">
      <span class="mask bg-gradient-info opacity-5"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto"></div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,1" />
          </g>
        </svg>
      </div>
    </div>
  </header>
<section class="py-7">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
      {% if dish.picture %}
        <img src="{{ dish.picture.url }}" alt="" style="width: 250px">
      {% endif %}
        <h3 class="text-gradient text-primary mb-0 mt-2">{{ dish.name }}</h3>
        <br>
        <h6>Price: {{ dish.price }} Category: {{ dish.category.name }}</h6>
        <p>{{ dish.description }}</p>
      {% if request.user.position == "Chef" %}
        <div class="row">
          <div class="col-md-4">
          <a href="{% url "kitchen:dish-update" pk=dish.id %}" class="btn btn-sm btn-outline-info">Update</a>
          </div>
          <div class="col-md-4" style="padding: unset">
            <a href="{% url "kitchen:dish-delete" pk=dish.id %}" class="btn btn-sm btn-outline-danger">Delete</a>
          </div>
        </div>
      {% endif %}
        <div class="d-block">
          {% if dish in user.dishes.all %}
            <a href="{% url "kitchen:toggle-dish-assign" pk=dish.id %}" class="btn btn-sm btn-outline-danger">Delete from my dish list</a>
          {% else %}
            <a href="{% url "kitchen:toggle-dish-assign" pk=dish.id %}" class="btn btn-sm btn-outline-primary">Add to my dish list</a>
          {% endif %}
        </div>
      </div>
      <div class="col-lg-6 mt-lg-0 mt-5 ps-lg-0 ps-0">
        {% if dish.cooks.all %}
          <h3>This dish can be prepared by:</h3>
        {% for cook in dish.cooks.all %}
          {% if cook %}
            <div class="row">
              <div class="p-3 info-horizontal">
                <div class="icon icon-shape rounded-circle bg-gradient-dark shadow text-center">
                  <i class="fas fa-user opacity-10"></i>
                </div>
                <div class="description ps-3">
                  <div class="row">
                  <div class="col-md-6">
                    <h4 class="mb-0">{{ cook.first_name }} {{ cook.last_name }}</h4>
                  </div>
                    {% if request.user.position == "Chef" %}
                      <div class="col-md-4">
                        <a href="{% url "kitchen:remove_cook_from_dish" dish_id=dish.id cook_id=cook.id %}">
                          <i class="fas fa-times opacity-6"></i>
                        </a>
                      </div>
                    {% endif %}
                    </div>
                  <p><strong>Username:</strong> {{ cook.username }} <strong> Year of experience:</strong> {{ cook.year_of_experience }}</p>
                </div>
              </div>
            </div>
          {% else %} <p>There are no cooks!</p>
          {% endif %}
        {% endfor %}
        {% else %}
          <p><strong>Oops, nobody cooks this dish!</strong></p>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock content %}
<div class="row">